version: '3.9'
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: task-manager
      TZ: America/Sao_Paulo
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - task-manager-network
  task-manager:
    image: rafayudi/task-manager
    restart: always
    build: ./Task-Manager
    working_dir: /Task-Manager
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: ${DB_URL}
      SPRING.DATASOURCE.USERNAME: ${DB_USER}
      SPRING.DATASOURCE.PASSWORD: ${DB_PASSWORD}
    ports:
      - 8080:8080
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - task-manager-network
networks:
  task-manager-network:
    driver: bridge