version: '3.9'
services:
  db:
    image: mysql:8.0.29
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: ${DB_USER}
      MYSQL_USER: docker
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: task-manager
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - task-manager-network
  task-manager:
    image: rafayudi/task-manager
    restart: always
    build: ./Task-Manager
    working_dir: /Task-Manager
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/task-manager?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: ${DB_USER}
      SPRING.DATASOURCE.PASSWORD: ${DB_PASSWORD}
    ports:
      - 8080:8080
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - task-manager-network
networks:
  task-manager-network:
    driver: bridge