CREATE TABLE IF NOT EXISTS tb_users (
  id UUID NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL,
  name VARCHAR(255) DEFAULT NULL,
  password VARCHAR(255) DEFAULT NULL,
  username VARCHAR(255) DEFAULT NULL,
  role VARCHAR(10) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE (username)
);
