CREATE TABLE IF NOT EXISTS tb_tasks (
  id UUID NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NULL,
  description VARCHAR(255) DEFAULT NULL,
  end_at TIMESTAMPTZ DEFAULT NULL,
  id_user UUID DEFAULT NULL,
  priority VARCHAR(255) DEFAULT NULL,
  start_at TIMESTAMPTZ DEFAULT NULL,
  title VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (id)
);
